Further work

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,36 +1,41 @@
 #!/bin/bash
 
-STAGED_JS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".js(x|(-next)){0,1}$");
-STAGED_SASS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".((sa)|(sc)|c)ss$");
+NPMGLOBALROOT=$(npm root -g);
 ESLINT=$(which eslint);
 SASSLINT=$(which sass-lint);
+
+STAGED_JS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".js(x|(-next)){0,1}$");
+STAGED_SASS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".((sa)|(sc)|c)ss$");
+
+SASSLINTCONFIG="$NPMGLOBALROOT/sasslint-config-perform/.sass-lint.yml";
+ESLINTCONFIG="$NPMGLOBALROOT/eslint-config-perform/index.js";
 
 if [ -z "$STAGED_JS" ] && [ -z "$STAGED_SASS" ];
 then
   exit 0
 fi
 
-if [ ! -x "$ESLINT" ];
-then
-    printf "\033[41mPlease install ESlint\033[0m (npm i -g eslint)\n"
-    exit 1
-fi
-
-if [ ! -x "$SASSLINT" ];
-then
-    printf "\033[41mPlease install Sass Lint\033[0m (npm install -g sass-lint)\n"
-    exit 1
-fi
-
 VALIDJS=true
 
 if [ ! -z "$STAGED_JS" ];
 then
-    printf "\nValidating JavaScript files:\n"
+    if [ ! -x "$ESLINT" ];
+    then
+        printf "\033[41mPlease install ESlint\033[0m (npm i -g eslint)\n"
+        exit 1
+    fi
+
+    if [ ! -f "$ESLINTCONFIG" ];
+    then
+        printf "\033[41mPlease install ESLint Perform config\033[0m (npm install -g git+ssh://git@github.com:performgroup/frontend-eslint-config-perform.git#1.0.1)\n"
+        exit 1
+    fi
+
+    printf "\n\x1B[34mValidating JavaScript files:\033[0m\n"
 
     for FILEJS in $STAGED_JS;
     do
-        "$ESLINT" "$FILEJS"
+        $ESLINT $FILEJS
 
         if [ "$?" == 0 ];
         then
@@ -43,14 +48,25 @@ VALIDSASS=true
 
 if [ ! -z "$STAGED_SASS" ];
 then
-    printf "\nValidating SASS files:\n"
+    if [ ! -x "$SASSLINT" ];
+    then
+        printf "\033[41mPlease install Sass Lint\033[0m (npm install -g sass-lint)\n"
+        exit 1
+    fi
+
+    if [ ! -f "$SASSLINTCONFIG" ];
+    then
+        printf "\033[41mPlease install Sass Lint Perform config\033[0m (npm install -g git+ssh://git@github.com:performgroup/frontend-sasslint-config-perform.git#1.0.2)\n"
+        exit 1
+    fi
+
+    printf "\n\x1B[34mValidating SASS files:\033[0m\n"
 
     for FILESASS in $STAGED_SASS;
     do
-        printf "$SASSLINT"
-        "$SASSLINT" "$FILESASS" "--verbose --no-exit"
+        $SASSLINT $FILESASS --config $SASSLINTCONFIG --verbose --no-exit
 
-        if [[ "$?" != 0 ]];
+        if [ "$?" == 0 ];
         then
             VALIDSASS=false
         fi
@@ -61,5 +77,7 @@ if [ "$VALIDJS" == 0 ] && [ "$VALIDSASS" == 0 ];
 then
   exit 0
 fi
+
+printf "\n\033[33mUnable to commit, please fix all errors occured\033[0m\n\n"
 
 exit 1
